services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - Bot__Token=${BOT_TOKEN}
      - Bot__InstagramSessionId=${INSTAGRAM_SESSION_ID}
    volumes:
      - ./cookies:/app/cookies
      - ./data:/app/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
